spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qoraa_db
    username: qoraa_user
    password: qoraa_password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      pool-name: QoraaHikariPool
